spring.application.name=HR Backend
spring.datasource.url=jdbc:postgresql://localhost:5432/fuzzystrmatch
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect